baseURL = 'https://sebaguardian.github.io'
defaultContentLanguage = "en"
title = 'Sebaguardian'
theme = "hugo-bearcub"
copyright = "Sebaguardian (MIT License)"
enableRobotsTXT = true

# not sure what this does, check out later ~ adam
[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false

[languages]
  [languages.en]
    languageName = "english"
    LanguageCode = "en-US"
    contentDir = "content"
  # [languages.pl]
  #   languageName = "polish"
  #   LanguageCode = "pl-PL"
  #   contentDir = "content.pl"
    [languages.en.params]
      madeWith = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"

[params]
  description = "My website"

  # favicon = "images/favicon.png"
  # openGraph and that kinda stuff
  # images = ["images/share.webp"]

  title = "Sebaguardian"
  dateFormat = "2006-01-02"
  hideUntranslated = false
  themeStyle = "original"

  # generateSocialCard = true
  # [params.social]
  #   twitter = "example" # Twitter handle (without '@')
  #   facebook_admin = "0000000000" # Facebook Page Admin ID

  [params.author]
    name = "Sebaguardian"
    # email = "me@example.com"
